
export const FETCH_LANGUAGES_REQUEST =`FETCH_LANGUAGES_REQUEST`;
export const FETCH_LANGUAGES_SUCCESS =`FETCH_LANGUAGES_SUCCESS`;
export const FETCH_LANGUAGES_ERROR =`FETCH_LANGUAGES_ERROR`;

export const FETCH_SKILLS_REQUEST =`FETCH_SKILLS_REQUEST`;
export const FETCH_SKILLS_SUCCESS =`FETCH_SKILLS_SUCCESS`;
export const FETCH_SKILLS_ERROR =`FETCH_SKILLS_ERROR`;

export const FETCH_ABOUTS_REQUEST =`FETCH_ABOUTS_REQUEST`;
export const FETCH_ABOUTS_SUCCESS =`FETCH_ABOUTS_SUCCESS`;
export const FETCH_ABOUTS_ERROR =`FETCH_ABOUTS_ERROR`;

export const FETCH_EXPERIENCES_REQUEST =`FETCH_EXPERIENCES_REQUEST`;
export const FETCH_EXPERIENCES_SUCCESS =`FETCH_EXPERIENCES_SUCCESS`;
export const FETCH_EXPERIENCES_ERROR =`FETCH_EXPERIENCES_ERROR`;

export const FETCH_EDUCATION_REQUEST =`FETCH_EDUCATION_REQUEST`;
export const FETCH_EDUCATION_SUCCESS =`FETCH_EDUCATION_SUCCESS`;
export const FETCH_EDUCATION_ERROR =`FETCH_EDUCATION_ERROR`;